// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhKf-0WTQGGt_GdHtrJea84Lp5xaMddkA',
    appId: '1:928905323402:web:9637271e590802b21ade73',
    messagingSenderId: '928905323402',
    projectId: 'advmobprog-firebase-85a76',
    authDomain: 'advmobprog-firebase-85a76.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-85a76.firebasestorage.app',
    measurementId: 'G-D8NZPWGLKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAnfFHErypCtsaR7SMZchdOMDHF1tzyBE',
    appId: '1:928905323402:android:4ebb39f45ecba5421ade73',
    messagingSenderId: '928905323402',
    projectId: 'advmobprog-firebase-85a76',
    storageBucket: 'advmobprog-firebase-85a76.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6pAF782KNLp_S3Ja-SnednyIwUHBCbwI',
    appId: '1:928905323402:ios:d976cab302d8f2531ade73',
    messagingSenderId: '928905323402',
    projectId: 'advmobprog-firebase-85a76',
    storageBucket: 'advmobprog-firebase-85a76.firebasestorage.app',
    iosBundleId: 'com.example.alonzoMobile',
  );
}
